name: Lint

# Run on push
on:
  push:

  workflow_dispatch:

jobs:
  luacheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run luacheck
        uses: nebularg/actions-luacheck@v1.1.2
        with:
          files: src/
          args: --include-files "**/*.ti" --no-global --no-max-line-length
